### ISSUE TITLE
An error occurred while installing dependencies`.

### ISSUE THREAD

**Issue by Hosar** [ui-storybook/sb#29]
Hello I'm getting just:
Installing dependencies. ?
    An error occurred while installing dependencies`.

How can I view errors logs, or more details about what's happening?
The error messages don't say too much.

- Angular 1.5.x
- Webpack 1.12.14
- Node v6.10.2
- typescript 1.8.10
- tsc 2.2.2

**Comment by tv1ster** [comment]
I have the same error. 
I tried to install all packages by my own, but i faced a lot of errors regarding packages version. For example, i needed to decrease webpack version for running server. But then i've got issues with other packages.

Can we have dependencies inserted in package.json on 'sb-create'?
Because right now inserted only 
`    "ui-storybook": "^1.0.5",
    "ng-annotate-loader": "0.0.10",
    "webpack-hot-middleware": "2.13.0"`

Or have it in package.json of ui-storybook. Because right now almost all dependencies are '*'.
